(* should return true *)
let z = fun () ->
  try
    raise Failure
  with
    Exception -> false

in
  try
    z ()
  with
    Failure -> true
